import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import UserContextProdiver from "./context/userContextprovider";
import WifiContextProvider from "./context/wifiContextprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProdiver>
          <WifiContextProvider>
        {children}
          </WifiContextProvider>
        </UserContextProdiver>
        <Toaster />
      </body>
    </html>
  );
}
